### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by pilchat** [LucaMalavolta/PyORBIT#19]
In https://pyorbit.readthedocs.io/en/latest/installation.html I couldn't find any instructions for the installation of PyORBIT. For python dummies like me, here they are:

- install the python package "cython" as it is required for the compilation of PyORBIT:

$ pip install cython

- clone and compile PyORBIT:

$ git clone https://github.com/LucaMalavolta/PyORBIT.git
$ cd PyORBIT/
$ python setup.py install

- then you should be able to import PyORBIT inside python:

>>> import pyorbit

- enjoy!

**Comment by LucaMalavolta** [comment]
Thanks,
Although PyORBIT can be imported and executed within a Python script, it is much easier to use the scripts provided in the main folder in combination with a _yaml_ configuration file, for example:

$ python /path/to/main/PyORBIT_Run.py emcee config.yaml > config_emcee.log
$ python /path/to/main/PyORBIT_GetResults.py emcee config.yaml -all > configemcee_getresults.log

Cheers,
Luca
