### ISSUE TITLE
cheops_modelling `scale_factor` boundaries

### ISSUE THREAD

**Issue by lucaborsato** [LucaMalavolta/PyORBIT#71]
In file `cheops_modelling.py` the parameter `scale_factor` has defaults:

```python
parameters_dictionary = {
    'scale_factor':
        {
            'bounds': [-5., 20.],
            'priors': ['Uniform', []],
            'spaces': 'Log_Base2',
            'fixed' : 1.00,
            'unit': None,
        },
```

when `PyORBIT` check and set the bounds of this parameter, it finds that the required space is `Log_Base2` and it applies `np.log2` to a negative argument return `nan`.
I suggest the following change:
```python
parameters_dictionary = {
    'scale_factor':
        {
            'bounds': [-5., 20.],
            'priors': ['Uniform', []],
            'spaces': 'Linear',
            'fixed' : 1.00,
            'unit': None,
        },
```

**Comment by LucaMalavolta** [comment]
I'm not sure if this value is supposed to be always positive or if it can assume negative values. I changed it to "Linear" as suggested, in case it is always possible to change its boundaries or its parameter space.
