### ISSUE TITLE
cheops_factormodel `scale_factor` not used

### ISSUE THREAD

**Issue by lucaborsato** [LucaMalavolta/PyORBIT#72]
In the file `cheops_factormodel.py` the parameter `scale_factor` is not used in the computation of the model factor.
The method `def compute(self, ...)` returns:
```python
return trend * parameter_values['dfdbg']
```
but it should return:
```python
return trend * parameter_values['scale_factor']
```

**Comment by LucaMalavolta** [comment]
This issue is corrected starting from version 10.3
